# Generated by Django 5.2.3 on 2025-06-11 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCoreColourCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rgb_value', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="RGB value must be in the format 'R,G,B' where R, G, and B are integers between 0 and 255 inclusive.", regex='^(?:([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]),){2}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$')])),
                ('hex_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Enter a valid hex color code (e.g., '#FFFFFF').", regex='^#[0-9A-Fa-f]{6}$')])),
            ],
            options={
                'verbose_name': 'System Core Color Code',
                'verbose_name_plural': 'System Core Color Codes',
            },
        ),
    ]
