# Generated by Django 5.2.3 on 2025-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RJ45Pinout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin_number', models.PositiveSmallIntegerField()),
                ('color_code', models.CharField(choices=[('WHITE ORANGE', 'White Orange'), ('ORANGE', 'Orange'), ('WHITE GREEN', 'White Green'), ('BLUE', 'Blue'), ('WHITE BLUE', 'White Blue'), ('GREEN', 'Green'), ('WHITE BROWN', 'White Brown'), ('BROWN', 'Brown')], max_length=20)),
            ],
            options={
                'verbose_name': 'RJ45 Pinout',
                'verbose_name_plural': 'RJ45 Pinouts',
                'unique_together': {('name', 'color_code'), ('name', 'pin_number')},
            },
        ),
    ]
