# Generated by Django 5.2.3 on 2025-06-12 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcorecolourcode',
            name='hex_code',
            field=models.CharField(help_text="Enter a valid hex color code (e.g., '#FFFFFF').", max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid hex color code (e.g., '#FFFFFF').", regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Hex Code'),
        ),
        migrations.AlterField(
            model_name='systemcorecolourcode',
            name='rgb_value',
            field=models.CharField(help_text="Enter a valid RGB value in the format 'R,G,B' (e.g., '255,255,255').", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="RGB value must be in the format 'R,G,B' where R, G, and B are integers between 0 and 255 inclusive.", regex='^(?:([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]),){2}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$')], verbose_name='RGB Value'),
        ),
    ]
