# Generated by Django 5.2.3 on 2025-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0003_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
