# Generated by Django 5.2.3 on 2025-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0004_remove_supplier_id_alter_supplier_supplier_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
