# Generated by Django 5.2.3 on 2025-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0005_remove_supplier_address_supplier_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_manufacturer',
            field=models.BooleanField(default=False, verbose_name='Is Manufacturer'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Supplier Code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
