# Generated by Django 5.2.3 on 2025-06-12 11:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0008_alter_country_iso_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Product Code')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('supplier_product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Product Code')),
                ('manufacturer_product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer Product Code')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('quantity_per_unit', models.PositiveIntegerField(default=1, verbose_name='Quantity Per Unit (e.g. per pack)')),
                ('unit', models.CharField(default='pcs', max_length=50, verbose_name='Unit (e.g. pcs, pack, box)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_products', to='systemcore.supplier', verbose_name='Manufacturer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemcore.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
