# Generated by Django 5.2.3 on 2025-06-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cable Name')),
                ('type', models.CharField(choices=[('CAT5', 'Cat 5'), ('CAT5E', 'Cat 5e'), ('CAT6', 'Cat 6'), ('CAT6A', 'Cat 6a'), ('CAT7', 'Cat 7'), ('CAT8', 'Cat 8')], max_length=10, verbose_name='Cable Type')),
                ('gbps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Speed (Gbps)')),
                ('mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Speed (Mbps)')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemcore.systemcorecolourcode', verbose_name='Color Code')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product Code')),
            ],
            options={
                'verbose_name': 'Cable',
                'verbose_name_plural': 'Cables',
                'ordering': ['name'],
            },
        ),
    ]
