# Generated by Django 5.2.3 on 2025-06-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0011_cable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatRJ45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FEMALE', 'RJ45 Female'), ('MALE', 'RJ45 Male')], max_length=6, verbose_name='Connector Type')),
                ('name', models.CharField(max_length=100, verbose_name='Connector Name')),
                ('pinout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.rj45pinout', verbose_name='Pinout')),
            ],
            options={
                'verbose_name': 'Cat RJ45 Connector',
                'verbose_name_plural': 'Cat RJ45 Connectors',
                'ordering': ['name'],
            },
        ),
    ]
