# Generated by Django 5.2.3 on 2025-06-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0012_catrj45'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Terminal Name')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product Code')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerminalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.PositiveSmallIntegerField(verbose_name='Input Number')),
                ('catrj45', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.catrj45', verbose_name='RJ45 Connector')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='systemcore.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Terminal Input',
                'verbose_name_plural': 'Terminal Inputs',
                'ordering': ['terminal', 'input_number'],
                'unique_together': {('terminal', 'input_number')},
            },
        ),
    ]
