# Generated by Django 5.2.3 on 2025-06-12 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0013_terminal_terminalinput'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBuilder',
            fields=[
                ('systemBuildNumber', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='System Build Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is Complete')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.client', verbose_name='Client')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Designer')),
            ],
            options={
                'verbose_name': 'System Build',
                'verbose_name_plural': 'System Builds',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SystemPurchaseOrder',
            fields=[
                ('purchase_order_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Purchase Order Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Is Ordered')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('system_builder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='systemcore.systembuilder', verbose_name='System Build')),
            ],
            options={
                'verbose_name': 'System Purchase Order',
                'verbose_name_plural': 'System Purchase Orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SystemPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('cable_length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cable Length (m)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='systemcore.systempurchaseorder', verbose_name='Purchase Order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemcore.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'System Purchase Order Item',
                'verbose_name_plural': 'System Purchase Order Items',
            },
        ),
        migrations.CreateModel(
            name='SystemBuilderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sequence', models.CharField(max_length=7, verbose_name='Connection Code Sequence')),
                ('label', models.CharField(max_length=100, verbose_name='Label (e.g. TV, Port 1)')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.cable', verbose_name='Cable')),
                ('system_builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='systemcore.systembuilder', verbose_name='System Build')),
                ('terminal_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_a_connections', to='systemcore.terminal', verbose_name='Terminal A')),
                ('terminal_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_b_connections', to='systemcore.terminal', verbose_name='Terminal B')),
            ],
            options={
                'verbose_name': 'System Build Connection',
                'verbose_name_plural': 'System Build Connections',
                'unique_together': {('system_builder', 'code_sequence')},
            },
        ),
    ]
