# Generated by Django 5.2.3 on 2025-06-12 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0014_systembuilder_systempurchaseorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemClientInvoice',
            fields=[
                ('invoice_number', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Invoice Number')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('system_builder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='systemcore.systembuilder', verbose_name='System Build')),
            ],
            options={
                'verbose_name': 'System Client Invoice',
                'verbose_name_plural': 'System Client Invoices',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SystemClientInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Amount')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('cable_length', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cable Length (m)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='systemcore.systemclientinvoice', verbose_name='Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'System Client Invoice Item',
                'verbose_name_plural': 'System Client Invoice Items',
            },
        ),
    ]
