# Generated by Django 5.2.3 on 2025-06-12 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0015_systemclientinvoice_systemclientinvoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Account Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Account',
                'verbose_name_plural': 'System Accounts',
            },
        ),
        migrations.AlterField(
            model_name='cable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemcore.product', verbose_name='Product Code'),
        ),
        migrations.CreateModel(
            name='SystemAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVOICE_PAYMENT', 'Invoice Payment (Money In)'), ('PURCHASE_ORDER_PAYMENT', 'Purchase Order Payment (Money Out)'), ('BILL', 'Bill (Money Out)'), ('CREDIT', 'Credit (Money In)')], max_length=32, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='systemcore.systemaccount', verbose_name='Account')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemcore.systemclientinvoice', verbose_name='Related Invoice')),
                ('related_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systemcore.systempurchaseorder', verbose_name='Related Purchase Order')),
            ],
            options={
                'verbose_name': 'System Account Transaction',
                'verbose_name_plural': 'System Account Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='systemcore.systemaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'System Bill',
                'verbose_name_plural': 'System Bills',
            },
        ),
        migrations.CreateModel(
            name='SystemCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='systemcore.systemaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'System Credit',
                'verbose_name_plural': 'System Credits',
            },
        ),
    ]
