# Generated by Django 5.2.3 on 2025-06-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0002_alter_systemcorecolourcode_hex_code_and_more'),
        ('systemcore', '0016_systemaccount_alter_cable_product_and_more'),
    ]

    operations = [
    ]
