# Generated by Django 5.2.3 on 2025-06-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcore', '0017_merge_20250613_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rj45pinout',
            options={'ordering': ['name'], 'verbose_name': 'RJ45 Pinout', 'verbose_name_plural': 'RJ45 Pinouts'},
        ),
        migrations.AlterUniqueTogether(
            name='rj45pinout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rj45pinout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-13 12:00:00', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rj45pinout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rj45pinout_images/', verbose_name='Pinout Image'),
        ),
        migrations.AddField(
            model_name='rj45pinout',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='rj45pinout',
            name='standards',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Standards'),
        ),
        migrations.AddField(
            model_name='rj45pinout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='rj45pinout',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='rj45pinout',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='rj45pinout',
            name='pin_number',
        ),
        migrations.CreateModel(
            name='RJ45Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.PositiveSmallIntegerField()),
                ('color_code', models.CharField(choices=[('WHITE ORANGE', 'White Orange'), ('ORANGE', 'Orange'), ('WHITE GREEN', 'White Green'), ('BLUE', 'Blue'), ('WHITE BLUE', 'White Blue'), ('GREEN', 'Green'), ('WHITE BROWN', 'White Brown'), ('BROWN', 'Brown')], max_length=20)),
                ('pinout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='systemcore.rj45pinout', verbose_name='Pinout')),
            ],
            options={
                'verbose_name': 'RJ45 Pin',
                'verbose_name_plural': 'RJ45 Pins',
                'ordering': ['pinout', 'pin_number'],
                'unique_together': {('pinout', 'pin_number')},
            },
        ),
    ]
